services:
  - type: web
    name: analizador-lectura-free
    runtime: python
    plan: free
    branch: main
    buildCommand: |
      pip install -r requirements-free.txt
      python -c "import whisper; whisper.load_model('base')"
    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port 8000 --workers 1
    envVars:
      - key: SUPABASE_URL
        value: your-supabase-url
      - key: SUPABASE_KEY
        value: your-supabase-key
    healthCheckPath: /health
    autoDeploy: true