services:
  - type: web
    name: analizador-audio-free
    runtime: python
    plan: free
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      python -c "import whisper; whisper.load_model('base')"
    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port 8000 --workers 1
    envVars:
      - key: SUPABASE_URL
        value: VITE_SUPABASE_URL=https://qdlmwuflfniifrmeoadl.supabase.co
      - key: SUPABASE_KEY
        value: VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkbG13dWZsZm5paWZybWVvYWRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNDg0MDQsImV4cCI6MjA1NzgyNDQwNH0.HESG9PdRiG2U_4HuKOMx4QOXi3hCy1Z5eF24JI3kMZw
    healthCheckPath: /health